### ISSUE TITLE
When you exit, the session disappears

### ISSUE THREAD

**Issue by Gofreedom0** [Ne0nd0g/merlin#109] opened 2021-06-13 06:18 UTC
After the Merlin server exits and enters again, the Merlin agent and listener will not be displayed. It is recommended to save the listening configuration of the Merlin server

![image](https://user-images.githubusercontent.com/22413346/121797275-d4d3ce00-cc51-11eb-882a-5328368ac1bc.png)
![image](https://user-images.githubusercontent.com/22413346/121797298-ffbe2200-cc51-11eb-9e03-489cd1c3acfd.png)
![image](https://user-images.githubusercontent.com/22413346/121797313-0f3d6b00-cc52-11eb-955a-e6d05719c755.png)

**Comment by Ne0nd0g** [comment] 2021-06-15 17:24
Duplicate of https://github.com/Ne0nd0g/merlin/issues/105

**Closed** 2021-06-15 17:25 UTC
